language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer update
  - mysql -e "create database calendar"
  - php artisan serve --port=8080

script: vendor/bin/behat

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
