language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - phpenv config-add travis.ini
  - "mysql -e 'create database `test_calendar`;'"
  - composer install -n --prefer-source
  - php artisan migrate --seed
  - php codecept build

script: php codecept run
