language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - sudo sed -i -e "/DocumentRoot/i\ServerName knpu_qa.l" /etc/apache2/sites-available/default
  - echo "127.0.0.1 netdev.gamingcalendar.com" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart
  - composer install --prefer-dist --no-interaction

script: vendor/bin/behat

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover